name: onboard_er
description: A Flutter onboarding package using bloc.
version: 0.1.1
repository: https://github.com/Developeryilmaz/onboard_er
homepage: https://github.com/Developeryilmaz/onboard_er

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  clay_containers: ^0.3.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  lottie: ^3.3.1
  permission_handler: ^11.4.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0  # Linter ve analiz için
  flutter_lints: ^5.0.0


flutter:

